### ISSUE TITLE
How to handle ENF_ACTION_TYPE_ISSUED

### ISSUE THREAD

**Issue by r-b-g-b** [r-b-g-b/clean-water-tool#11]
There are several types of  `ENF_ACTION_TYPE_ISSUED`. How should we handle those as they relate to #7 (deduplication).

| enforcement action name | number of records
| ----- | -----
| FORMAL ENFORCEMENT ACTION ISSUED | 5009
| STATE INTENTIONAL NO ACTION TAKEN | 356
| OTHER INFORMAL ENFORCEMENT ACTION TAKEN | 311
| INFORMAL ENFORCEMENT ACTION ISSUED | 204
| CA STATE ACTION ISSUED | 169
| FORMAL ENFORCEMENT ACTION WITH PENALTY ISSUED | 62
| US EPA FEDERAL ADMINSTRATIVE ORDER ON CONSENT | 27

Do all of these indicate going out of compliance? That is, can I treat them all identically?

**Comment by ruckeralex** [comment]
Per the SWRCB and CWC, at this level of analysis we can treat all enforcement actions identically, as long as they are not "RETURN TO COMPLIANCE."

**Comment by r-b-g-b** [comment]
Perfect, thanks! Closing.
