### ISSUE TITLE
Refactor dedupe code to src for master code flow

### ISSUE THREAD

**Issue by skyballin** [r-b-g-b/clean-water-tool#17]
I wanted to keep all of the 'finished' code pieces in the src folder so we can have a 'master routine' going. 

ie. the dedupe logic to create the active violations table is now in 'active_violations.py' and outputs a csv file to 'data/output/'

**Comment by skyballin** [comment]
PR # 18

**Comment by r-b-g-b** [comment]
Closed by #18
