### ISSUE TITLE
Create downloadable .csv file of query results from online reporting tool

### ISSUE THREAD

**Issue by ruckeralex** [r-b-g-b/clean-water-tool#23]
Create function to download an .xls file of the query results from #24 .  In addition to the fields in the HR2W raw data set, the downloadable .xls file will also provide the following calculated fields:  whether system is in Tulare Lake Basin, the absolute # of exceedance of analyte [ = "RESULT" - "MCL"], and the % exceedance of the analyte [("RESULT" - "MCL") / "MCL"].

Aaron and/or Robert, is this something you can help produce?

**Comment by sharkberto** [comment]
@ruckeralex @aaronhans in branch export-button i've still got a little more logic to implement to create a csv from data in #24 (system, city, county, zip, analyte)

To be able to grab the information at the system level, there should be some additional processing to query into it. Does the user click into the system level info and grab the csv, or do they click at the level they see the five fields in #24

**Comment by sharkberto** [comment]
What I mean is, do they grab a csv at system level page: https://aaronhans.github.io/community-water-center/system.html?id=CA0900102 (example) ?

**Comment by ruckeralex** [comment]
Hi Alex!  Is it possible for the users to have the option to download CSV file on both pages-- the main page (https://aaronhans.github.io/community-water-center/) and on the Water System-level page (https://aaronhans.github.io/community-water-center/system.html?id=CA3710009)?  In both cases, perhaps you can offer a link to "Download .csv file of displayed data" above the first data table.

**Comment by sharkberto** [comment]
Hi @ruckeralex ! we have a basic button implemented which I'll work to merge into `master`. Last thing is working on calculated results to close this out.

**Comment by sharkberto** [comment]
This issue can be closed once https://github.com/openoakland/clean-water/pull/1/commits is merged (new repo). There may be some error handling still to do to, e.g. to account for calculations where there is any missing data, but the functionality and additional fields are in place

**Comment by ruckeralex** [comment]
Wow! Amazing!!  Thank you so much!

How can we merge/create new repo so we can see this change?

Cheers,
Rucker

On Aug 7, 2019, at 9:22 AM, Alex <notifications@github.com> wrote:

This issue can be closed once https://github.com/openoakland/clean-water/pull/1/commits is merged (new repo). There may be some error handling still to do to, e.g. to account for calculations where there is any missing data, but the functionality and additional fields are in place
