### ISSUE TITLE
Create query fields for 5+ characteristics

### ISSUE THREAD

**Issue by ruckeralex** [r-b-g-b/clean-water-tool#24]
Create query fields in the online reporting tool interface for 5 searchable characteristics: water system name, county, city, zip code, and analyte.  

Once the water systems are tagged with legislative districts and regional boards (see #22 ), add these fields too.

Users can select one or more characteristics and the tool will show a list of all water system names that have violations (within that given reporting period).

**Comment by r-b-g-b** [comment]
A simple version of this could just refer to files stored at different locations, like:

thing.github.io/WATERSYSTEMNAME/ANALYTE serves up info for the given water system and analyte.

but I think to be fully queryable along all of those dimensions we will actually need to put it all in a database, which will I think mean we can no longer serve the whole thing through github pages. Curious to hear your thoughts @aaronhans @skyballin ?

**Comment by aaronhans** [comment]
I am able to make the current json queryable by those 5 keys parsing the json with javascript setting the unique names in those fields as map keys, demo: https://aaronhans.github.io/community-water-center/

**Comment by r-b-g-b** [comment]
Ohhhh dang, that's awesome!

**Comment by ruckeralex** [comment]
Yay!  That sounds very promising!  Thank you Aaron!
